GET http://localhost:8080/api/runs

### Find Runs by location
GET http://localhost:8080/api/runs/location/INDOOR

### Find By ID that doesn't exist
GET http://localhost:8080/api/runs/1

### Create invalid run throws error
POST http://localhost:8080/api/runs
Content-Type: application/json

{
  "id": 19,
  "title": "Dawn Run",
  "startedOn": "2025-03-09T01:34:00",
  "completedOn": "2025-03-08T05:53:00",
  "miles": 27,
  "location": "OUTDOOR"
}